version: 2
sources:
 - name: ergast
   schema: public
   tables:
     - name: races
       identifier: races
     - name: pitstops
       identifier: pitstops
     - name: results
       identifier: results
     - name: drivers
       identifier: drivers
     - name: constructors
       identifier: constructors